In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\srmve\\Downloads\\loan.CSV (1).csv")
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [4]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [5]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
df=df.drop('Loan_ID',axis =1)
df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [7]:
from sklearn. preprocessing import LabelEncoder
label_encoder = LabelEncoder ()
categorical_columns = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area',
'Loan_Status']
df[categorical_columns] = df[categorical_columns]. apply(label_encoder.fit_transform)
df[categorical_columns]

Gender  Married  Education  Self_Employed  Property_Area  Loan_Status
0         1        0          0              0              2            1
1         1        1          0              0              0            0
2         1        1          0              1              2            1
3         1        1          1              0              2            1
4         1        0          0              0              2            1
..      ...      ...        ...            ...            ...          ...
609       0        0          0              0              0            1
610       1        1          0              0              0            1
611       1        1          0              0              2            1
612       1        1          0              0              2            1
613       0        0          0              1              1            0

[614 rows x 6 columns]

In [8]:
from sklearn.impute import SimpleImputer
numeric_columns = ['Gender', 'Married','Dependents', 'Self_Employed', 'LoanAmount',
'Loan_Amount_Term', 'Credit_History']
df[numeric_columns] = SimpleImputer(strategy='most_frequent').fit_transform(df[numeric_columns])
df[numeric_columns]

Gender Married Dependents Self_Employed LoanAmount Loan_Amount_Term  \
0        1       0          0             0      120.0            360.0   
1        1       1          1             0      128.0            360.0   
2        1       1          0             1       66.0            360.0   
3        1       1          0             0      120.0            360.0   
4        1       0          0             0      141.0            360.0   
..     ...     ...        ...           ...        ...              ...   
609      0       0          0             0       71.0            360.0   
610      1       1         3+             0       40.0            180.0   
611      1       1          1             0      253.0            360.0   
612      1       1          2             0      187.0            360.0   
613      0       0          0             1      133.0            360.0   

    Credit_History  
0              1.0  
1              1.0  
2              1.0  
3              1.0  
4              1.0  
..             ...  
609            1.0  
610            1.0  
611            1.0  
612            1.0  
613            0.0  

[614 rows x 7 columns]

In [9]:
df['Dependents'] = df['Dependents']. replace ('3+', 3). astype(float)
df['Dependents']

0      0.0
1      1.0
2      0.0
3      0.0
4      0.0
      ... 
609    0.0
610    3.0
611    1.0
612    2.0
613    0.0
Name: Dependents, Length: 614, dtype: float64

In [10]:
x=df.iloc[:,:-1]
x

Gender Married  Dependents  Education Self_Employed  ApplicantIncome  \
0        1       0         0.0          0             0             5849   
1        1       1         1.0          0             0             4583   
2        1       1         0.0          0             1             3000   
3        1       1         0.0          1             0             2583   
4        1       0         0.0          0             0             6000   
..     ...     ...         ...        ...           ...              ...   
609      0       0         0.0          0             0             2900   
610      1       1         3.0          0             0             4106   
611      1       1         1.0          0             0             8072   
612      1       1         2.0          0             0             7583   
613      0       0         0.0          0             1             4583   

     CoapplicantIncome LoanAmount Loan_Amount_Term Credit_History  \
0                  0.0      120.0            360.0            1.0   
1               1508.0      128.0            360.0            1.0   
2                  0.0       66.0            360.0            1.0   
3               2358.0      120.0            360.0            1.0   
4                  0.0      141.0            360.0            1.0   
..                 ...        ...              ...            ...   
609                0.0       71.0            360.0            1.0   
610                0.0       40.0            180.0            1.0   
611              240.0      253.0            360.0            1.0   
612                0.0      187.0            360.0            1.0   
613                0.0      133.0            360.0            0.0   

     Property_Area  
0                2  
1                0  
2                2  
3                2  
4                2  
..             ...  
609              0  
610              0  
611              2  
612              2  
613              1  

[614 rows x 11 columns]

In [11]:
y=df.iloc[:,-1]
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int32

In [12]:
from sklearn. model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split (x, y, random_state=0)

In [13]:
from sklearn. preprocessing import StandardScaler
scaler = StandardScaler ()
x_train = scaler.fit_transform(x_train)
x_test = scaler. transform(x_test)
x_train

array([[ 0.36547961,  0.6622422 ,  0.20631248, ...,  0.27778225,
         0.41649656,  1.20186498],
       [ 0.36547961, -1.42427431, -0.77207659, ...,  0.27778225,
         0.41649656, -1.31684978],
       [ 0.36547961, -1.42427431,  1.18470154, ...,  0.27778225,
         0.41649656, -1.31684978],
       ...,
       [ 0.36547961,  0.6622422 ,  2.1630906 , ...,  0.27778225,
         0.41649656, -0.0574924 ],
       [ 0.36547961,  0.6622422 , -0.77207659, ...,  0.27778225,
         0.41649656,  1.20186498],
       [-2.00241646,  0.6622422 , -0.77207659, ...,  0.27778225,
         0.41649656, -0.0574924 ]])

In [14]:
x_test

array([[ 0.36547961, -1.42427431, -0.77207659, ...,  0.27778225,
         0.41649656, -0.0574924 ],
       [-2.00241646, -1.42427431, -0.77207659, ...,  0.27778225,
         0.41649656, -0.0574924 ],
       [ 0.36547961,  0.6622422 , -0.77207659, ...,  0.27778225,
         0.41649656,  1.20186498],
       ...,
       [ 0.36547961,  0.6622422 , -0.77207659, ...,  0.27778225,
         0.41649656,  1.20186498],
       [ 0.36547961, -1.42427431, -0.77207659, ...,  0.27778225,
         0.41649656, -0.0574924 ],
       [ 0.36547961,  0.6622422 ,  0.20631248, ...,  0.27778225,
        -2.40098019, -0.0574924 ]])

In [15]:
from sklearn. linear_model import LogisticRegression
model = LogisticRegression ()

In [16]:
model.fit (x_train, y_train)

LogisticRegression()

In [17]:
y_pred=model. predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0])

In [18]:
from sklearn. metrics import accuracy_score, classification_report
accuracy = accuracy_score (y_test, y_pred) * 100
print ("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 83.77


In [19]:
from sklearn. metrics import classification_report
class_report = classification_report (y_test, y_pred)
print (f"\nClassification Report:\n{class_report}")


Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.47      0.62        43
           1       0.83      0.98      0.90       111

    accuracy                           0.84       154
   macro avg       0.87      0.72      0.76       154
weighted avg       0.85      0.84      0.82       154



In [20]:
new_data = [1, 1, 2, 1, 1, 4106.0, 240.0, 253.0, 360.0, 1, 2]
predictions = model. predict([new_data])
print(predictions)

[1]


In [21]:
decoded_predictions = label_encoder. inverse_transform(predictions)
print(decoded_predictions)

['Y']
