In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.simplefilter("ignore")

In [3]:
df=pd.read_csv("C:\\Users\\srmve\\Downloads\\Traffic.csv")
df.head()

Time  Date Day of the week  CarCount  BikeCount  BusCount  \
0  12:00:00 AM    10         Tuesday        31          0         4   
1  12:15:00 AM    10         Tuesday        49          0         3   
2  12:30:00 AM    10         Tuesday        46          0         3   
3  12:45:00 AM    10         Tuesday        51          0         2   
4   1:00:00 AM    10         Tuesday        57          6        15   

   TruckCount  Total Traffic Situation  
0           4     39               low  
1           3     55               low  
2           6     55               low  
3           5     58               low  
4          16     94            normal

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2976 entries, 0 to 2975
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Time               2976 non-null   object
 1   Date               2976 non-null   int64 
 2   Day of the week    2976 non-null   object
 3   CarCount           2976 non-null   int64 
 4   BikeCount          2976 non-null   int64 
 5   BusCount           2976 non-null   int64 
 6   TruckCount         2976 non-null   int64 
 7   Total              2976 non-null   int64 
 8   Traffic Situation  2976 non-null   object
dtypes: int64(6), object(3)
memory usage: 209.4+ KB


In [5]:
df.describe()

Date     CarCount    BikeCount     BusCount   TruckCount  \
count  2976.000000  2976.000000  2976.000000  2976.000000  2976.000000   
mean     16.000000    68.696573    14.917339    15.279570    15.324933   
std       8.945775    45.850693    12.847518    14.341986    10.603833   
min       1.000000     6.000000     0.000000     0.000000     0.000000   
25%       8.000000    19.000000     5.000000     1.000000     6.000000   
50%      16.000000    64.000000    12.000000    12.000000    14.000000   
75%      24.000000   107.000000    22.000000    25.000000    23.000000   
max      31.000000   180.000000    70.000000    50.000000    40.000000   

             Total  
count  2976.000000  
mean    114.218414  
std      60.190627  
min      21.000000  
25%      55.000000  
50%     109.000000  
75%     164.000000  
max     279.000000

In [6]:
df.isnull().sum()

Time                 0
Date                 0
Day of the week      0
CarCount             0
BikeCount            0
BusCount             0
TruckCount           0
Total                0
Traffic Situation    0
dtype: int64

In [7]:
df=df.drop('Time',axis=1)
df.head()

Date Day of the week  CarCount  BikeCount  BusCount  TruckCount  Total  \
0    10         Tuesday        31          0         4           4     39   
1    10         Tuesday        49          0         3           3     55   
2    10         Tuesday        46          0         3           6     55   
3    10         Tuesday        51          0         2           5     58   
4    10         Tuesday        57          6        15          16     94   

  Traffic Situation  
0               low  
1               low  
2               low  
3               low  
4            normal

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
categorical_columns=['Day of the week','Traffic Situation']
df[categorical_columns]=df[categorical_columns].apply(label_encoder.fit_transform)
df[categorical_columns]

Day of the week  Traffic Situation
0                   5                  2
1                   5                  2
2                   5                  2
3                   5                  2
4                   5                  3
...               ...                ...
2971                4                  3
2972                4                  3
2973                4                  3
2974                4                  3
2975                4                  3

[2976 rows x 2 columns]

In [9]:
x=df.iloc[:,:-1]
x

Date  Day of the week  CarCount  BikeCount  BusCount  TruckCount  Total
0       10                5        31          0         4           4     39
1       10                5        49          0         3           3     55
2       10                5        46          0         3           6     55
3       10                5        51          0         2           5     58
4       10                5        57          6        15          16     94
...    ...              ...       ...        ...       ...         ...    ...
2971     9                4        16          3         1          36     56
2972     9                4        11          0         1          30     42
2973     9                4        15          4         1          25     45
2974     9                4        16          5         0          27     48
2975     9                4        14          3         1          15     33

[2976 rows x 7 columns]

In [10]:
y=df.iloc[:,-1]
y

0       2
1       2
2       2
3       2
4       3
       ..
2971    3
2972    3
2973    3
2974    3
2975    3
Name: Traffic Situation, Length: 2976, dtype: int32

In [15]:
from sklearn. model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split (x, y, random_state=0)

In [16]:
from sklearn. preprocessing import StandardScaler
scaler = StandardScaler ()
x_train = scaler.fit_transform(x_train)
x_test = scaler. transform(x_test)
x_train

array([[-0.33600687, -1.59798223,  1.98010887, ...,  1.00899718,
        -1.1633432 ,  2.0733575 ],
       [ 0.43635908, -1.59798223,  2.30697357, ..., -0.31203497,
        -1.1633432 ,  2.20601196],
       [ 1.42940101, -0.10771914,  1.10846967, ...,  0.66135714,
        -0.68866549,  0.8628855 ],
       ...,
       [ 1.20872503, -1.59798223, -0.351526  , ..., -0.590147  ,
        -0.02411669, -0.48024096],
       [-1.10837282, -1.10122786, -1.15779226, ..., -1.07684306,
         0.83030319, -1.1766769 ],
       [-0.99803483,  0.88578959,  0.01892066, ..., -0.72920302,
         1.30498091, -0.09885937]])

In [17]:
x_test

array([[-0.99803483,  0.88578959, -1.24495618, ..., -1.07684306,
         1.21004537, -1.19325871],
       [-1.66006278,  1.38254396,  0.38936732, ...,  0.17466108,
         1.39991645,  0.43175849],
       [-1.32904881, -0.6044735 , -0.22078012, ...,  1.2175812 ,
         0.92523874,  0.21619498],
       ...,
       [ 1.31906302, -0.6044735 , -1.07062834, ..., -0.17297896,
         0.64043211, -0.91136797],
       [ 0.32602109,  0.38903523, -1.13600128, ..., -1.00731505,
         0.45056102, -1.20984052],
       [-1.4393868 , -1.59798223, -0.351526  , ..., -0.79873103,
        -0.02411669, -0.57973181]])

In [19]:
from sklearn.svm import SVC
model = SVC (kernel = 'linear', random_state = 0)

In [20]:
model.fit (x_train, y_train)

SVC(kernel='linear', random_state=0)

In [21]:
y_pred=model. predict(x_test)
y_pred

array([3, 1, 1, 0, 3, 3, 3, 0, 0, 3, 0, 3, 0, 3, 3, 0, 1, 0, 2, 3, 3, 1,
       3, 2, 3, 0, 3, 3, 2, 0, 0, 3, 3, 3, 0, 0, 3, 0, 0, 3, 0, 0, 2, 3,
       0, 3, 3, 0, 3, 3, 3, 0, 3, 0, 3, 0, 3, 0, 3, 3, 3, 0, 3, 3, 2, 0,
       3, 3, 2, 0, 1, 0, 2, 3, 3, 2, 3, 0, 3, 3, 3, 0, 0, 3, 3, 0, 2, 3,
       3, 0, 0, 3, 2, 3, 3, 0, 3, 1, 1, 3, 0, 0, 3, 3, 3, 0, 3, 3, 3, 3,
       3, 0, 3, 1, 3, 3, 0, 3, 3, 0, 3, 3, 0, 3, 3, 3, 2, 3, 0, 3, 0, 3,
       0, 0, 3, 3, 3, 0, 3, 3, 0, 3, 1, 3, 2, 2, 3, 0, 3, 3, 0, 3, 3, 2,
       3, 2, 2, 0, 3, 3, 2, 3, 0, 3, 3, 3, 3, 3, 1, 3, 3, 2, 3, 2, 0, 3,
       0, 3, 3, 0, 3, 3, 0, 3, 0, 1, 1, 3, 0, 0, 3, 3, 2, 0, 0, 0, 2, 3,
       0, 3, 3, 1, 1, 1, 3, 3, 3, 1, 3, 3, 3, 1, 0, 0, 1, 2, 2, 1, 3, 0,
       3, 3, 3, 3, 0, 3, 1, 3, 3, 0, 3, 3, 3, 0, 3, 2, 2, 3, 0, 3, 3, 1,
       3, 3, 3, 1, 1, 1, 1, 3, 0, 3, 3, 3, 3, 0, 3, 3, 0, 3, 0, 3, 3, 0,
       3, 3, 3, 1, 0, 1, 2, 3, 3, 2, 0, 3, 3, 3, 0, 1, 0, 3, 3, 3, 1, 3,
       0, 3, 1, 3, 0, 3, 3, 3, 3, 3, 3, 0, 0, 2, 0,

In [22]:
from sklearn. metrics import accuracy_score, classification_report
accuracy = accuracy_score (y_test, y_pred) * 100
print ("Accuracy of the model is {:.2f}",format(accuracy))

Accuracy of the model is {:.2f} 89.24731182795699


In [23]:
from sklearn. metrics import classification_report
class_report = classification_report (y_test, y_pred)
print (f"\nClassification Report:\n{class_report}")


Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       168
           1       0.85      0.75      0.79        80
           2       0.72      0.68      0.70        73
           3       0.90      0.92      0.91       423

    accuracy                           0.89       744
   macro avg       0.86      0.84      0.84       744
weighted avg       0.89      0.89      0.89       744



In [24]:
new_data = [9, 5, 6, 3, 2, 5, 45]
predictions = model. predict([new_data])
print(predictions)

[0]


In [25]:
decoded_predictions = label_encoder.inverse_transform(predictions)
print(decoded_predictions)

['heavy']
