In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter("ignore")

In [3]:
df=pd.read_csv("C:\\Users\\srmve\\Downloads\\Trip (2).csv")

In [4]:
df.head()

Duration        Start date          End date  Start station number  \
0      1012  20-09-2010 11:27  20-09-2010 11:43                 31208   
1        61  20-09-2010 11:41  20-09-2010 11:42                 31209   
2      2690  20-09-2010 12:05  20-09-2010 12:50                 31600   
3      1406  20-09-2010 12:06  20-09-2010 12:29                 31600   
4      1413  20-09-2010 12:10  20-09-2010 12:34                 31100   

                   Start station  End station number  \
0       M St & New Jersey Ave SE               31108   
1                 1st & N St  SE               31209   
2                  5th & K St NW               31100   
3                  5th & K St NW               31602   
4  19th St & Pennsylvania Ave NW               31201   

                     End station Bike number Member type  
0                  4th & M St SW      W00742      Member  
1                 1st & N St  SE      W00032      Member  
2  19th St & Pennsylvania Ave NW      W00993      Member  
3        Park Rd & Holmead Pl NW      W00344      Member  
4                 15th & P St NW      W00883      Member

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115597 entries, 0 to 115596
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   Duration              115597 non-null  int64 
 1   Start date            115597 non-null  object
 2   End date              115597 non-null  object
 3   Start station number  115597 non-null  int64 
 4   Start station         115597 non-null  object
 5   End station number    115597 non-null  int64 
 6   End station           115597 non-null  object
 7   Bike number           115597 non-null  object
 8   Member type           115597 non-null  object
dtypes: int64(3), object(6)
memory usage: 7.9+ MB


In [6]:

df.describe()

Duration  Start station number  End station number
count  115597.000000         115597.000000       115597.000000
mean     1254.649956          31266.213431        31268.042250
std      2914.317998            187.645048          186.194316
min        60.000000          31000.000000        31000.000000
25%       403.000000          31110.000000        31111.000000
50%       665.000000          31213.000000        31214.000000
75%      1120.000000          31301.000000        31238.000000
max     85644.000000          31805.000000        31805.000000

In [7]:
df.isnull().sum()

Duration                0
Start date              0
End date                0
Start station number    0
Start station           0
End station number      0
End station             0
Bike number             0
Member type             0
dtype: int64

In [8]:
df=df.drop(['Start date','End date'],axis=1)
df.head()

Duration  Start station number                  Start station  \
0      1012                 31208       M St & New Jersey Ave SE   
1        61                 31209                 1st & N St  SE   
2      2690                 31600                  5th & K St NW   
3      1406                 31600                  5th & K St NW   
4      1413                 31100  19th St & Pennsylvania Ave NW   

   End station number                    End station Bike number Member type  
0               31108                  4th & M St SW      W00742      Member  
1               31209                 1st & N St  SE      W00032      Member  
2               31100  19th St & Pennsylvania Ave NW      W00993      Member  
3               31602        Park Rd & Holmead Pl NW      W00344      Member  
4               31201                 15th & P St NW      W00883      Member

In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
categorical_columns=['Start station','End station','Bike number','Member type']
df[categorical_columns]=df[categorical_columns].apply(label_encoder.fit_transform)
df[categorical_columns].head()

Start station  End station  Bike number  Member type
0             85           50          614            1
1             32           33           41            1
2             52           31          836            1
3             52           94          282            1
4             30           21          734            1

In [10]:
x=df.iloc[:,:-1]
x

Duration  Start station number  Start station  End station number  \
0           1012                 31208             85               31108   
1             61                 31209             32               31209   
2           2690                 31600             52               31100   
3           1406                 31600             52               31602   
4           1413                 31100             30               31201   
...          ...                   ...            ...                 ...   
115592      2179                 31110             35               31623   
115593       953                 31106             63               31401   
115594       737                 31602             93               31401   
115595       514                 31111              1               31202   
115596     51962                 31111              1               31111   

        End station  Bike number  
0                50          614  
1                33           41  
2                31          836  
3                94          282  
4                21          734  
...             ...          ...  
115592           65          716  
115593           18          764  
115594           18          819  
115595           14          946  
115596            1          636  

[115597 rows x 6 columns]

In [11]:
y=df.iloc[:,-1]
y

0         1
1         1
2         1
3         1
4         1
         ..
115592    0
115593    1
115594    1
115595    1
115596    0
Name: Member type, Length: 115597, dtype: int32

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.54640202, -1.40804138, -0.50762432,  1.8909801 ,  0.11621975,
        -1.36635173],
       [-0.32533639, -1.41337456, -0.81044688, -1.36975376,  0.69092124,
        -1.47913197],
       [-0.14892163, -0.28274243, -0.84409383, -0.89702793, -1.10079519,
         1.07843294],
       ...,
       [-0.21022131, -0.16007951, -0.13750786, -0.30074876, -0.35706384,
        -1.51915077],
       [-0.18028425,  1.85052573,  0.77095983,  1.86949256, -0.05281011,
         0.57637894],
       [-0.35277869, -0.35207365,  1.30931104, -0.35983949, -0.93176534,
         0.82740594]])

In [14]:
x_test

array([[-0.36026295, -0.82672581, -1.58432676, -0.20942672,  1.43465259,
        -0.78789821],
       [ 0.00682231, -0.84272532,  0.0307269 , -0.2524018 , -0.76273549,
         0.74736835],
       [-0.28648951, -0.35207365,  1.30931104, -0.88091228,  0.2852496 ,
        -0.93705918],
       ...,
       [-0.12254851, -0.83205898, -0.44033042, -0.26314557, -1.57407878,
         1.63141995],
       [-0.2815    , -0.32540779, -0.40668346, -0.34909572, -1.13460116,
        -1.46457968],
       [-0.16887966, -0.85872483, -1.21421029, -0.29000499, -0.8641534 ,
        -1.01709678]])

In [15]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [16]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [17]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 1, 0])

In [18]:
from sklearn.metrics import accuracy_score,classification_report
accuracy=accuracy_score(y_test,y_pred)*100
print("Accurcy of the model is {:.2f}", format(accuracy))

Accurcy of the model is {:.2f} 79.8166089965398


In [19]:
from  sklearn.metrics import classification_report
class_report=classification_report(y_test,y_pred)
print(f"Classification report: {class_report}")

Classification report:               precision    recall  f1-score   support

           0       0.52      0.54      0.53      6089
           1       0.88      0.87      0.87     22811

    accuracy                           0.80     28900
   macro avg       0.70      0.70      0.70     28900
weighted avg       0.80      0.80      0.80     28900



In [20]:
new_data=[737,31110,63,31623,18,636]
predictions=model.predict([new_data])
print([predictions])

[array([1])]


In [21]:
decoded_predictions=label_encoder.inverse_transform([predictions])
print(decoded_predictions)

['Member']
